### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BlagoYar** [R1KO/LocalBans#5]
При компиляции такие ошибки

`// LocalBans/util.sp(271) : warning 203: symbol is never used: "iClient"

// LocalBans/cmds.sp(44) : error 029: invalid expression, assumed zero
// LocalBans/cmds.sp(50) : warning 225: unreachable code`

Можно ли поправить?

**Comment by R1KO** [comment]
@BlagoYar юзай эту версию https://gitlab.com/R1KO/LocalBans/tree/add_logs

**Comment by BlagoYar** [comment]
> @BlagoYar юзай эту версию https://gitlab.com/R1KO/LocalBans/tree/add_logs

БлагоДарю, испытаю.

ПС. Если что, то ошибки и другое туда же отписывать?

**Comment by R1KO** [comment]
@BlagoYar лучше на гитлаб и писать

**Comment by BlagoYar** [comment]
> @BlagoYar лучше на гитлаб и писать

Отписался там по тем же ошибкам, но уже с той версии gitlab
